### PR TITLE
fix: add aws provisioner to controlplane.

### LINKED ISSUE #1781: AWS Provisioner Runtime Dependency Missing from edc-controlplane-base
## Describe the bug

We distribute the Tractus-X connector with a dataplane capable of handling both azure and aws related transfers. Despite including the azure provisioner in the controlplane runtime [the AWS one](https://github.com/eclipse-edc/Technology-Aws/blob/0cd2022d393640b068ea63e8f71e68c1fa5b9e6f/extensions/control-plane/provision/provision-aws-s3/src/main/java/org/eclipse/edc/connector/provision/aws/s3/AwsProvisionExtension.java#L36) is not included.

As a result the dataspace consumer AWS credentials are directly sent to the provider, as no temporary credentials (usually created during provisioning) are generated. This results in a potential security concern.

### To Reproduce

Perform a TP using an AWS service (ex:S3).

### Expected behavior

Creation of temp credentials instead of provider receiving the consumer's AWS credentials.

## Possible Implementation

Include the AWS provision dependency in the edc-controlplane-base.

### PR DESCRIPTION
**Pull request by bmg13**
## WHAT

This PR adds the AWS Provisioner Dependency to edc-controlplane-base.

## WHY

To use AWS S3 Provisioner when performing transfer using AWS S3 Service.

## FURTHER NOTES

Added the `datadestination` to the transfer process in the tests due to NPE's resulting from [this](https://github.com/eclipse-edc/Technology-Aws/blob/f9e2d9c5f9420f3c65395085bedca38be723fcb9/extensions/control-plane/provision/provision-aws-s3/src/main/java/org/eclipse/edc/connector/provision/aws/s3/S3ConsumerResourceDefinitionGenerator.java#L53) validation.

Added the LocalStackExtension since the S3 E2E tests pass through [this](https://github.com/eclipse-edc/Technology-Aws/blob/f53a4fd4a37f748e5d9bd06885d0315764232058/extensions/control-plane/provision/provision-aws-s3/src/main/java/org/eclipse/edc/connector/provision/aws/s3/S3ProvisionPipeline.java#L107) flow and mocking of IAM is required. Since MinIO is unable to do it (it "only" mocks S3), the inclusion of LocalStack is needed.
Left still the usage of MinIO since it covers other tests and its removal torwards using ony LocalStack should be its own issue.

Closes #1781

### CODE REVIEW

**Comment by rafaelmag110** [comment]
If they are not being used i'm in favor of removing them, as that will make the code simpler.

**Comment by bmg13** [comment]
> If they are not being used i'm in favor of removing them, as that will make the code simpler.

Very fair, thank you, updated in [here](https://github.com/eclipse-tractusx/tractusx-edc/pull/2020/commits/86438b00a026082a72b33c5bc5829fc38cd5a209).

File: edc-tests/e2e/end2end-transfer-cloud/src/test/java/org/eclipse/tractusx/edc/tests/transfer/S3ToS3EndToEndTest.java [hunk 1]
```diff
@@ -118,25 +117,73 @@ void transferFile_success() {
...
+                "objectName", TESTFILE_NAME,
+                "region", PROVIDER_CONTAINER.getS3region(),
+                "bucketName", sourceBucketName,
+                "accessKeyId", PROVIDER_CONTAINER.getCredentials().accessKeyId(),
+                "secretAccessKey", PROVIDER_CONTAINER.getCredentials().secretAccessKey(),
+                "endpointOverride", PROVIDER_CONTAINER.getEndpointOverride()
+        );
+
+        PROVIDER.createAsset(assetId, Map.of(), dataAddress);
+        var policyId = PROVIDER.createPolicyDefinition(bnpPolicy(CONSUMER.getBpn()));
```
Comment (rafaelmag110) [inline edc-tests/e2e/end2end-transfer-cloud/src/test/java/org/eclipse/tractusx/edc/tests/transfer/S3ToS3EndToEndTest.java:159]:
```suggestion
        var policyId = PROVIDER.createPolicyDefinition(bpnPolicy(CONSUMER.getBpn()));
```

Please change other occurrences too

Comment (bmg13) [reply edc-tests/e2e/end2end-transfer-cloud/src/test/java/org/eclipse/tractusx/edc/tests/transfer/S3ToS3EndToEndTest.java]: Changed every reference in [here](https://github.com/eclipse-tractusx/tractusx-edc/pull/2020/commits/0e191148c0a8bcde1095a4597e618d65b8b23d22).

**Review by rafaelmag110 — APPROVED** [review]
