### PR TITLE
fix: revoke refresh token method now deletes secret

### LINKED ISSUE #1602: Refresh token secret never deleted from vault
## Describe the bug

When a refresh token is revoked (because the dataflow was terminated), it removes the token metadata from the `accessTokenStore`.
However the actual refresh tokens are never deleted from the vault where they are stored, hence living indefinitely.

### To Reproduce

As a consumer, start an `HttpData-PULL` transfer process.
On the provider side, verify refresh token secret was created
Terminate transfer process on consumer side.
Verify secret still exists.

### Expected behavior

Secret should be deleted.

## Possible Implementation

Add `vault.deleteSecret()` on `DataPlaneTokenRefreshServiceImpl.deleteTokenData()`

### PR DESCRIPTION
**Pull request by rafaelmag110**
## WHAT

This PR adds the missing deletion of the token refresh secret.

## WHY

It was not being deleted.

Closes #1602

### CODE REVIEW

File: edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/main/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceImpl.java [hunk 1]
```diff
@@ -270,6 +270,11 @@ public Result<Void> revoke(String transferProcessId, String reason) {
     }
 
     private Result<Void> deleteTokenData(AccessTokenData tokenData) {
+        var deletionResult = vault.deleteSecret(tokenData.id());
+        if (deletionResult.failed()) {
+            return Result.failure(deletionResult.getFailureMessages());
```
Comment (paullatzelsperger) [inline edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/main/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceImpl.java:275]: no need to instantiate a new `Result`:
```suggestion
            return deletionResult;
```

File: edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/test/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceImplComponentTest.java [hunk 2]
```diff
@@ -303,6 +310,22 @@ void resolve_notFound() {
...
 
+    @Test
+    void revoke_successful() throws JsonProcessingException {
+        var tokenId = "token-id";
+        var transferProcessId = "dummy-tp-id";
+        var accessTokenData = new AccessTokenData(tokenId, ClaimToken.Builder.newInstance().claim("claim1", "value1").build(),
+                DataAddress.Builder.newInstance().type("type").build(), Map.of("process_id", transferProcessId));
+
+        tokenDataStore.store(accessTokenData);
+        vault.storeSecret(tokenId, objectMapper.writeValueAsString(mock(RefreshToken.class)));
```
Comment (paullatzelsperger) [inline edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/test/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceImplComponentTest.java:321]: no not mock value objects.

**Review by paullatzelsperger — CHANGES_REQUESTED** [review]

**Review by paullatzelsperger — APPROVED** [review]
