### PR TITLE
feat: introduce TxParticipant + E2E tests fix

### LINKED ISSUE #963: Refactor E2E tests runtimes/configuration
## WHAT

Refactor the E2E tests infrastructure by using the EDC upstream `Participant`

## WHY

cleanup

### PR DESCRIPTION
**Pull request by wolf4ood**
## WHAT

In this PR:

- Upgrade to EDC `0.4.2-20240103-SNAPSHOT` (preparing for IATP integration)
- Refactor the Participant and E2E tests configurations by using the upstream EDC participant

## WHY

IATP adotpion, E2E clean up

Closes #963

### CODE REVIEW

File: edc-extensions/data-encryption/src/test/java/org/eclipse/tractusx/edc/data/encryption/TxEncryptorExtensionTest.java [hunk 1]
```diff
@@ -49,7 +48,7 @@ class TxEncryptorExtensionTest {
     @BeforeEach
     void setup(ObjectFactory factory, ServiceExtensionContext c) {
         c.registerService(Monitor.class, monitor);
-        context = spy(c);
+        context = c;
```
Comment (paullatzelsperger) [inline edc-extensions/data-encryption/src/test/java/org/eclipse/tractusx/edc/data/encryption/TxEncryptorExtensionTest.java:51]: do we need the `context` at all? we can inject it directly as method arg if needed.

File: edc-extensions/edr/edr-cache-sql/src/test/java/org/eclipse/tractusx/edc/edr/store/sql/SqlEndpointDataReferenceCacheExtensionTest.java [hunk 2]
```diff
@@ -42,7 +41,7 @@ public class SqlEndpointDataReferenceCacheExtensionTest {
 
     @BeforeEach
     void setUp(ObjectFactory factory, ServiceExtensionContext context) {
-        this.context = spy(context);
+        this.context = context;
```
Comment (paullatzelsperger) [inline edc-extensions/edr/edr-cache-sql/src/test/java/org/eclipse/tractusx/edc/edr/store/sql/SqlEndpointDataReferenceCacheExtensionTest.java:44]: needed?

File: edc-extensions/postgresql-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/policy/V0_0_4__Add_Private_Properties.sql [hunk 3]
```diff
@@ -0,0 +1,15 @@
+--
+--  Copyright (c) 2022 Mercedes-Benz Tech Innovation GmbH
```
Comment (paullatzelsperger) [inline edc-extensions/postgresql-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/policy/V0_0_4__Add_Private_Properties.sql:2]: copyright header?

File: edc-extensions/ssi/ssi-identity-core/src/test/java/org/eclipse/tractusx/edc/iam/ssi/identity/SsiIdentityServiceExtensionTest.java [hunk 4]
```diff
@@ -41,7 +40,7 @@ public class SsiIdentityServiceExtensionTest {
 
     @BeforeEach
     void setup(ObjectFactory factory, ServiceExtensionContext context) {
-        this.context = spy(context);
+        this.context = context;
```
Comment (paullatzelsperger) [inline edc-extensions/ssi/ssi-identity-core/src/test/java/org/eclipse/tractusx/edc/iam/ssi/identity/SsiIdentityServiceExtensionTest.java:43]: needed anymore?

**Review by paullatzelsperger — APPROVED** [review]
LGTM, minor nits

File: edc-extensions/data-encryption/src/test/java/org/eclipse/tractusx/edc/data/encryption/TxEncryptorExtensionTest.java (hunk 1 above)
Comment (wolf4ood) [reply edc-extensions/data-encryption/src/test/java/org/eclipse/tractusx/edc/data/encryption/TxEncryptorExtensionTest.java:51]: Yeah i didn't want to change the tests so much, probably it's not needed, this was only done because tests where failing :). I would tackle all this other refactor in another PR. I guess there are others as well
