### PR TITLE
fix: ConnectorParamsDiscoveryResquest format

### LINKED ISSUE #2262: OpenAPI spec for connector discovery broken
## Describe the bug

The description of the new /v4alpha/connectordiscovery endpoint is broken in https://eclipse-tractusx.github.io/tractusx-edc/openapi/control-plane-api/#/Connector%20Discovery/discoverDspVersionParamsV4Alpha.

The endpoint address is wrong and the request body is not shown appropriately 

### To Reproduce

Check the url given above and observe the behavior

### Expected behavior

The OpenApi spec is correct

### PR DESCRIPTION
**Pull request by rafaelmag110**
## WHAT

Removes an unnecessary trailing comma from an ConnectorDiscoveryV4AlphaAPI example.

## WHY

It was messing with formatting in the Swagger UI for that particular example.

## FURTHER NOTES

Closes #2262

### CODE REVIEW

File: edc-extensions/connector-discovery/connector-discovery-api/src/main/java/org/eclipse/tractusx/edc/discovery/v4alpha/api/ConnectorDiscoveryV4AlphaApi.java [hunk 1]
```diff
@@ -56,7 +56,7 @@ public interface ConnectorDiscoveryV4AlphaApi {
     JsonObject discoverDspVersionParamsV4Alpha(JsonObject querySpecJson);
 
 
-    @Schema(name = "ConnectorParamsDiscoveryRequestSchema", example = ConnectorParamsDiscoveryRequestSchema.EXAMPLE)
+    @Schema(name = "ConnectorParamsDiscoveryRequest", example = ConnectorParamsDiscoveryRequestSchema.EXAMPLE)
```
Comment (rafaelmag110) [inline edc-extensions/connector-discovery/connector-discovery-api/src/main/java/org/eclipse/tractusx/edc/discovery/v4alpha/api/ConnectorDiscoveryV4AlphaApi.java:59]: Non related change, it's just a nitpick. I've done this just for consistency with other schemas.

**Review by bmg13 — APPROVED** [review]
